- name: 'Add docker host'
  hosts: localhost
  tasks:
      # Gather facts
      - name: 'Include global vars'
        include_vars:
            dir: ./../../vars/global
      - name: 'Check operating system'
        shell: uname
        ignore_errors: yes
        register: uname_result
      - add_host:
            env: "{{ env }}"
            hostname: "backend_app"
            ansible_connection: "docker"
            ansible_host: "{{ SHORT_PROJECT_NAME }}{{ (uname_result.stdout != 'Darwin')|ternary('_', '-') }}backend_app{{ (uname_result.stdout != 'Darwin')|ternary('_', '-') }}1"
            ansible_python_interpreter: "/usr/bin/python3"
- name: 'Connect to docker backend_app and apply migrations'
  hosts: backend_app
  remote_user: sail
  gather_facts: no
  tasks:
    # Gather facts
    - name: 'Include global vars'
      include_vars:
          dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
          dir: ./../../vars/{{ env }}
    - name: 'Apply migrations'
      raw: "php {{ APP_CODE_PATH_CONTAINER }}/artisan october:migrate --force"
